//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChromaKeyDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChromaKeyDemo.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chroma Key Demo is a Nokia Developer example demonstrating the Nokia Imaging SDK chroma key filter..
        /// </summary>
        public static string AboutPage_AboutRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_AboutRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap on the upper original viewfinder to select a chroma key color (for example a green backdrop canvas) and use the color distance slider to adjust the threshold of the color range to be made transparent. Tap on the lower modified viewfinder to toggle between a video background and a &quot;transparent&quot; background..
        /// </summary>
        public static string AboutPage_GuideRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_GuideRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Commons 3.0 Unported.
        /// </summary>
        public static string AboutPage_Hyperlink_CCBY30_Text {
            get {
                return ResourceManager.GetString("AboutPage_Hyperlink_CCBY30_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://creativecommons.org/licenses/by/3.0/.
        /// </summary>
        public static string AboutPage_Hyperlink_CCBY30_Url {
            get {
                return ResourceManager.GetString("AboutPage_Hyperlink_CCBY30_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://github.com/nokia-developer/chroma-key-demo/.
        /// </summary>
        public static string AboutPage_Hyperlink_Project_Url {
            get {
                return ResourceManager.GetString("AboutPage_Hyperlink_Project_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocean Trip.
        /// </summary>
        public static string AboutPage_Hyperlink_VideoSource_Text {
            get {
                return ResourceManager.GetString("AboutPage_Hyperlink_VideoSource_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.youtube.com/watch?v=nzgfOBTNye0.
        /// </summary>
        public static string AboutPage_Hyperlink_VideoSource_Url {
            get {
                return ResourceManager.GetString("AboutPage_Hyperlink_VideoSource_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zero-project.
        /// </summary>
        public static string AboutPage_Hyperlink_ZeroProject_Text {
            get {
                return ResourceManager.GetString("AboutPage_Hyperlink_ZeroProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.zero-project.gr/.
        /// </summary>
        public static string AboutPage_Hyperlink_ZeroProject_Url {
            get {
                return ResourceManager.GetString("AboutPage_Hyperlink_ZeroProject_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underwater background video used in this application is a short clip from {0}. The original video is copyright of the {1} and licensed under the {2} license..
        /// </summary>
        public static string AboutPage_LegalRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_LegalRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information and application source code go to {0}..
        /// </summary>
        public static string AboutPage_ProjectRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_ProjectRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPage_Title_Text {
            get {
                return ResourceManager.GetString("AboutPage_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chroma Key Demo version {0}.
        /// </summary>
        public static string AboutPage_VersionRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_VersionRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHROMA KEY DEMO.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string MainPage_AboutMenuItem_Text {
            get {
                return ResourceManager.GetString("MainPage_AboutMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string MainPage_ColorLabel {
            get {
                return ResourceManager.GetString("MainPage_ColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color distance.
        /// </summary>
        public static string MainPage_DistanceLabel {
            get {
                return ResourceManager.GetString("MainPage_DistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered result (tap to toggle transparency/video).
        /// </summary>
        public static string MainPage_FilteredLabel {
            get {
                return ResourceManager.GetString("MainPage_FilteredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        public static string MainPage_MaximumDistanceLabel {
            get {
                return ResourceManager.GetString("MainPage_MaximumDistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string MainPage_MinimumDistanceLabel {
            get {
                return ResourceManager.GetString("MainPage_MinimumDistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original (tap to choose color).
        /// </summary>
        public static string MainPage_ViewfinderLabel {
            get {
                return ResourceManager.GetString("MainPage_ViewfinderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
